#!/usr/bin/env bash
# Install nginx. on web server; Nginx should be listening on port 80

sudo apt update
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo ufw allow "Nginx HTTP"
sudo service nginx restart
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
