#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument.
#Accepts a string as an argument
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#Ping the IP 5 times

echo "Listening ports:"
netstat -lnt | awk '{print $4}' | cut -d ":" -f 2 | sort -u | while read port; do
    echo "Port: $port"
    pid=$(lsof -i:$port -sTCP:LISTEN -t)
    if [ -n "$pid" ]; then
        name=$(ps -p $pid -o comm=)
        echo "Program name: $name (PID: $pid)"
    else
        echo "No program is listening on this port"
    fi
done
