#!/usr/bin/env bash
#a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
pids=$(pgrep bash)
for pid in $pids; do
    name=$(cat /proc/$pid/cmdline | tr '\0' ' ')
    echo "PID: $pid, Name: $name"
done
