#!/usr/bin/env bash
# Set localhost to 127.0.0.2 in /etc/hosts
sed -i 's/^127\.0\.0\.1.*$/127.0.0.2\tlocalhost/' /etc/hosts

# Set facebook.com to 8.8.8.8 in /etc/hosts
sed -i 's/^.*facebook\.com.*$/8.8.8.8\tfacebook.com/' /etc/hosts

